# Generated by Django 5.2.14 on 2026-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Obecność potwierdzona'),
        ),
    ]
